const affirmations = [
  "I forgive myself and set myself free.",
  "I believe I can be all that I want to be.",
  "I am in the process of becoming the best version of myself.",
  "I have the freedom & power to create the life I desire.",
  "I choose to be kind to myself and love myself unconditionally.",
  "My possibilities are endless.",
  "I am worthy of my dreams.",
  "I am enough.",
  "I deserve to be healthy and feel good.",
  "I am full of energy and vitality and my mind is calm and peaceful.",
  "Every day I am getting healthier and stronger.",
  "I honor my body by trusting the signals that it sends me.",
  "I manifest perfect health by making smart choices.",
  "I am capable of achieving my goals.",
  "I am worthy of love and respect.",
  "I trust in my abilities.",
  "I am strong and resilient.",
  "I choose to focus on the positive.",
  "I am grateful for what I have.",
  "I am open to new opportunities.",
  "I am in control of my reactions.",
  "I am constantly growing and learning.",
  "I am at peace with myself.",
  "I attract positive energy.",
  "I release all that no longer serves me.",
  "I am confident in my decisions.",
  "I am deserving of happiness.",
  "I am healthy and vibrant."
]

const mantras = [
  "Breathing in, I send myself love. Breathing out, I send love to someone else who needs it.",
  "Don’t let yesterday take up too much of today.",
  "Every day is a second chance.",
  "Tell the truth and love everyone.",
  "I am free from sadness.",
  "I am enough.",
  "In the beginning it is you, in the middle it is you and in the end it is you.",
  "I love myself.",
  "I am present now.",
  "Inhale the future, exhale the past.",
  "This too shall pass.",
  "Yesterday is not today.",
  "The only constant is change.",
  "Onward and upward.",
  "I am the sky, the rest is weather.",
  "Peace within, peace without.",
  "I am centered, I am calm.",
  "One breath, one moment.",
  "I choose serenity.",
  "My heart is open.",
  "I am grounded and present.",
  "I release fear, I embrace love.",
  "I am safe, I am secure.",
  "I trust the process.",
  "I am strong, I am balanced.",
  "I find joy in the present.",
  "I am connected to my inner wisdom.",
  "Anything worth doing is worth doing poorly"
]